name: me_chat_app
description: A new Flutter project.


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'







dependencies:
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.4.5
  cupertino_icons: ^1.0.2
  emoji_picker_flutter: ^1.5.2
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  google_sign_in: ^6.0.2
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  ionicons: ^0.2.2
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter




flutter:

  
  
  
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/welcome.png
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
