// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2GpzJ1Dtc5m9lvt6mo1upiuV2yxCjWF4',
    appId: '1:322527088560:web:92bdee2c48bea7da691075',
    messagingSenderId: '322527088560',
    projectId: 'me-chat-b9c9f',
    authDomain: 'me-chat-b9c9f.firebaseapp.com',
    storageBucket: 'me-chat-b9c9f.appspot.com',
    measurementId: 'G-0VYST9MMQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu5_iadBvkVSyAH4eP0T7EDnC7xdhEii4',
    appId: '1:322527088560:android:f3462833dd0b6484691075',
    messagingSenderId: '322527088560',
    projectId: 'me-chat-b9c9f',
    storageBucket: 'me-chat-b9c9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhMtdVA3j0s3fmgcD4DZ2QONLr8o13sI0',
    appId: '1:322527088560:ios:69aa3d7add3116c9691075',
    messagingSenderId: '322527088560',
    projectId: 'me-chat-b9c9f',
    storageBucket: 'me-chat-b9c9f.appspot.com',
    iosClientId:
        '322527088560-dfr2i16llknsrdccrgh2a6i6l1hh0f2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.meChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhMtdVA3j0s3fmgcD4DZ2QONLr8o13sI0',
    appId: '1:322527088560:ios:69aa3d7add3116c9691075',
    messagingSenderId: '322527088560',
    projectId: 'me-chat-b9c9f',
    storageBucket: 'me-chat-b9c9f.appspot.com',
    iosClientId:
        '322527088560-dfr2i16llknsrdccrgh2a6i6l1hh0f2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.meChatApp',
  );
}
